### ISSUE TITLE
failure to clean up process

### ISSUE THREAD

**Issue by juztas** [cmscaltech/fdtcp#1]
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/Pyro-3.16-py2.7.egg/Pyro/protocol.py", line 1126, in connectionHandler
    if self.getAdapter().handleConnection(conn, self):
  File "/usr/lib/python2.7/site-packages/Pyro-3.16-py2.7.egg/Pyro/protocol.py", line 836, in handleConnection
    ver,body,pflags = self.receiveMsg(conn)
  File "/usr/lib/python2.7/site-packages/Pyro-3.16-py2.7.egg/Pyro/protocol.py", line 633, in receiveMsg
    self.returnException(conn, ProtocolError(msg))
  File "/usr/lib/python2.7/site-packages/Pyro-3.16-py2.7.egg/Pyro/protocol.py", line 813, in returnException
    pic=Pyro.util.getXMLPickle('gnosis')
  File "/usr/lib/python2.7/site-packages/Pyro-3.16-py2.7.egg/Pyro/util.py", line 435, in getXMLPickle
    raise NotImplementedError('xml pickling implementation (%s) is not available' % impl)
NotImplementedError: xml pickling implementation (gnosis) is not available
```

**Comment by juztas** [comment]
Not the case in Pyro4. To be superseeded by: https://github.com/cmscaltech/fdtcp/issues/3
